# Generated by Django 3.1.2 on 2020-10-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(0, 'Женский'), (1, 'Мужской')], null=True, verbose_name='пол')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
            ],
        ),
    ]
