# Generated by Django 3.1.2 on 2021-05-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.SmallIntegerField(choices=[(1, 'Онлайн'), (2, 'Оффлайн')], default=2, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='Местоположение')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта в градусах')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота в градусах')),
            ],
            options={
                'verbose_name': 'Телескоп',
                'verbose_name_plural': 'Телескопы',
            },
        ),
    ]
