# Generated by Django 3.1.2 on 2021-05-16 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_telescope_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Online'), (2, 'Offline')], default=2, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='BalanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(verbose_name='Требуемое время в минутах')),
                ('status', models.SmallIntegerField(choices=[(1, 'Создана'), (2, 'Одобрена'), (3, 'Отклонена')], default=1, verbose_name='Статус')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_requests', to='tasks.telescope', verbose_name='Телескоп')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0, verbose_name='Наблюдательное время')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='tasks.telescope', verbose_name='Телескоп')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Баланс наблюдательного времени',
                'verbose_name_plural': 'Балансы наблюдательного времени',
            },
        ),
    ]
