# Generated by Django 3.1.2 on 2021-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210516_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancerequest',
            options={'verbose_name': 'Заявка на получение наблюдательного времени', 'verbose_name_plural': 'Заявки на получение наблюдательного времени'},
        ),
        migrations.AlterField(
            model_name='task',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время конца наблюдения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала наблюдения'),
        ),
    ]
