# Generated by Django 3.1.2 on 2021-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210525_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tledata',
            name='satellite_name',
        ),
        migrations.AddField(
            model_name='tledata',
            name='satellite_id',
            field=models.IntegerField(default=1, verbose_name='Номер спутника'),
            preserve_default=False,
        ),
    ]
