# Generated by Django 3.1.2 on 2021-05-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210524_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='point',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='tledata',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TLE_data', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_data', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='trackpoint',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='track_points', to='tasks.task', verbose_name='Задание'),
        ),
    ]
