# Generated by Django 3.1.2 on 2021-06-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210601_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='results', verbose_name='Снимок')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tasks.frame', verbose_name='Фрейм')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tasks.point', verbose_name='Точка')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tasks.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Результаты наблюдений',
                'verbose_name_plural': 'Результаты наблюдений',
            },
        ),
    ]
